version: "3"
services:
  web:
    restart: always
    image: thaihoa311/egg-contact-book:1
    ports:
    - "7001:7001"
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/contact-book'
    depends_on:
    - mongo
  mongo:
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"